version: '3'
services:
    gpt_model:
      container_name: "gpt_model"
      user: root
      build:
        context:  ./model
      ports:
        - "6060:6060"

    aiogram:
      container_name: "gpt_aiogram_bot"
      build:
        context: aiogram
      ports:
        - "8082:8082"
      depends_on:
        - gpt_model
